# Generated by Django 5.0.3 on 2024-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_artist_avatar_alter_artist_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1111)),
            ],
        ),
    ]
