# Generated by Django 5.0.3 on 2024-04-04 10:22

import utils.coder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_a_test_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_test',
            name='img',
            field=models.ImageField(default=1, upload_to=utils.coder.encode_upload_image),
            preserve_default=False,
        ),
    ]
