# Generated by Django 5.0.3 on 2024-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_a_test_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
