# Generated by Django 5.0.3 on 2024-04-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_video_img_alter_song_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcomment',
            old_name='album',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='playcomment',
            old_name='album',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='songcomment',
            old_name='album',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='videocomment',
            old_name='album',
            new_name='video',
        ),
    ]
